import 'dart:convert';
import 'dart:io';

import 'package:rk/src/targets/homebrew/client.dart';
import 'package:rk/src/engine/assets.dart';
import 'package:rk/src/engine/ref_name.dart';
import 'package:rk/src/engine/tools.dart';
import 'package:rk/src/engine/verdict.dart';
import 'package:rk/src/engine/version.dart';
import 'package:rk/src/transforms/digest.dart';
import 'package:test/test.dart';

const _assets = {
  'macos-arm64': PlatformAsset(
    name: 'keybay-0.2.0-macos-arm64.tar.gz',
    sha256: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  ),
  'linux-x64': PlatformAsset(
    name: 'keybay-0.2.0-linux-x64.tar.gz',
    sha256: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  ),
  'linux-arm64': PlatformAsset(
    name: 'keybay-0.2.0-linux-arm64.tar.gz',
    sha256: 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ),
};

String render({Map<String, PlatformAsset> assets = _assets}) =>
    HomebrewCask.render(
      token: 'keybay',
      description: 'Secret storage for Dart',
      homepage: 'https://github.com/danReynolds/keybay',
      version: '0.2.0',
      repository: 'danReynolds/keybay',
      tag: 'keybay_cli-v0.2.0',
      assets: assets,
      executable: 'keybay',
    );

void main() {
  test('points at the release that produced the assets', () {
    final cask = render();
    expect(
      cask,
      contains('https://github.com/danReynolds/keybay/releases/download/'
          'keybay_cli-v0.2.0/keybay-0.2.0-macos-arm64.tar.gz'),
    );
    expect(cask, contains(_assets['macos-arm64']!.sha256));
  });

  test('selects the archive and checksum by OS and architecture', () {
    final cask = render();
    expect(cask, contains('on_macos do'));
    expect(cask, contains('depends_on arch: :arm64'));
    expect(cask, contains('on_linux do'));
    expect(cask, contains('arch arm: "arm64", intel: "x64"'));
    expect(cask, contains('sha256 arm64_linux:'));
    expect(cask, contains('x86_64_linux:'));
  });

  test('omits the checksum for a platform the release does not ship', () {
    final cask = render(assets: {'macos-arm64': _assets['macos-arm64']!});
    expect(cask, contains(_assets['macos-arm64']!.sha256));
    expect(cask, isNot(contains('on_linux do')));
    expect(cask, contains('depends_on :macos'));
  });

  test('a single Linux architecture is explicit and Linux-only', () {
    final cask = render(assets: {'linux-arm64': _assets['linux-arm64']!});
    expect(cask, contains('on_linux do'));
    expect(cask, contains('keybay-0.2.0-linux-arm64.tar.gz'));
    expect(cask, contains('depends_on arch: :arm64'));
    expect(cask, contains('depends_on :linux'));
    expect(cask, isNot(contains('on_macos do')));
  });

  test('refuses an archive outside the closed platform contract', () {
    expect(
      () => render(
        assets: const {
          'windows-x64': PlatformAsset(
            name: 'keybay-0.2.0-windows-x64.tar.gz',
            sha256: 'dddd',
          ),
        },
      ),
      throwsArgumentError,
    );
  });

  test('installs the released executable through the cask binary artifact', () {
    expect(render(), contains('binary "keybay"'));
  });

  test('says it is generated, and what editing it costs', () {
    final cask = render();
    expect(cask, contains('Generated by rk'));
    expect(cask, contains('next release stop'));
  });

  test('a quote cannot escape into the Ruby', () {
    final cask = HomebrewCask.render(
      token: 'keybay',
      description: 'A "quoted" description',
      homepage: 'https://example.com',
      version: '1.0.0',
      repository: 'a/b',
      tag: 'v1.0.0',
      assets: const {
        'macos-arm64': PlatformAsset(
          name: 'keybay-1.0.0-macos-arm64.tar.gz',
          sha256:
              'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        ),
      },
      executable: 'keybay',
    );
    expect(cask, contains(r'desc "A \"quoted\" description"'));
  });

  test('a Git-valid tag cannot become Ruby interpolation', () {
    const tag = r'v#{system("id")}-0.2.0';
    expect(refNameIssue(tag), isNull);
    final cask = HomebrewCask.render(
      token: 'keybay',
      description: 'Secret storage for Dart',
      homepage: 'https://github.com/danReynolds/keybay',
      version: '0.2.0',
      repository: 'danReynolds/keybay',
      tag: tag,
      assets: _assets,
      executable: 'keybay',
    );
    expect(cask, isNot(contains(r'#{system')));
    expect(cask, contains('v%23%7Bsystem'));
  });

  group('cask tokens follow Homebrew\'s convention', () {
    test('a simple name', () {
      expect(ReleaseAssets.caskToken('keybay'), 'keybay');
    });
    test('an underscored name', () {
      expect(ReleaseAssets.caskToken('keybay_cli'), 'keybay-cli');
    });
    test('a hyphenated name', () {
      expect(ReleaseAssets.caskToken('my-tool'), 'my-tool');
    });
  });

  group('the public cask target', () {
    List<int> generated(String version, String payload) => utf8.encode(
          '# Generated by rk.\n'
          '  version "$version"\n'
          '$payload\n',
        );

    HomebrewTarget target(List<int> publicBytes) => HomebrewTarget(
          tools: RecordingTools(
            answers: (key) => key.startsWith(
              'gh api repos/owner/homebrew-tap/contents/Casks/tool.rb',
            )
                ? ToolResult(
                    exitCode: 0,
                    stdout: jsonEncode({'content': base64Encode(publicBytes)}),
                    stderr: '',
                  )
                : null,
          ),
          tap: 'owner/homebrew-tap',
        );

    test('is exact only when every public cask byte agrees', () async {
      final expected = generated('1.0.0', 'sha256 "aaaa"');
      final result = await target(expected).inspect(
        caskPath: 'Casks/tool.rb',
        intendedVersion: Version.tryParse('1.0.0')!,
        expectedBytes: expected,
      );
      expect(result.verdict, Verdict.exact);
      expect(result.evidence['identity'], 'sha256:${Sha256.hex(expected)}');
    });

    test('is exact from an authenticated manifest digest without local bytes',
        () async {
      final public = generated('1.0.0', 'sha256 "aaaa"');
      final result = await target(public).inspect(
        caskPath: 'Casks/tool.rb',
        intendedVersion: Version.tryParse('1.0.0')!,
        expectedBytes: null,
        expectedSha256: Sha256.hex(public),
      );

      expect(result.verdict, Verdict.exact);
      expect(result.evidence['identity'], 'sha256:${Sha256.hex(public)}');
    });

    test('a recognizable older cask is ordinary forward work', () async {
      final older = generated('0.9.0', 'sha256 "older"');
      final result = await target(older).inspect(
        caskPath: 'Casks/tool.rb',
        intendedVersion: Version.tryParse('1.0.0')!,
        expectedBytes: generated('1.0.0', 'sha256 "new"'),
      );
      expect(result.verdict, Verdict.absent);
      expect(result.detail, contains('earlier version 0.9.0'));
      expect(result.authority, isA<HomebrewUpdateAuthority>());
      expect(
        (result.authority! as HomebrewUpdateAuthority).accepts(older),
        isTrue,
      );
    });

    test('a newer cask never rolls back', () async {
      final newer = generated('1.1.0', 'sha256 "newer"');
      final result = await target(newer).inspect(
        caskPath: 'Casks/tool.rb',
        intendedVersion: Version.tryParse('1.0.0')!,
        expectedBytes: generated('1.0.0', 'sha256 "expected"'),
      );
      expect(result.verdict, Verdict.conflict);
      expect(result.detail, contains('newer version 1.1.0'));
    });

    test('a hand edit is conflict even when the version still agrees',
        () async {
      final result = await target(
        generated('1.0.0', 'sha256 "hand-edited"'),
      ).inspect(
        caskPath: 'Casks/tool.rb',
        intendedVersion: Version.tryParse('1.0.0')!,
        expectedBytes: generated('1.0.0', 'sha256 "expected"'),
      );
      expect(result.verdict, Verdict.conflict);
      expect(result.evidence, contains('public identity'));
    });
  });

  group('cask version locator', () {
    test('reads one canonical version from generated bytes', () {
      expect(HomebrewCask.versionIn(utf8.encode(render())).toString(), '0.2.0');
    });

    test('does not treat hand-written or ambiguous bytes as generated', () {
      expect(HomebrewCask.versionIn(utf8.encode('version "0.2.0"\n')), isNull);
      expect(
        HomebrewCask.versionIn(utf8.encode(
          '# Generated by rk.\n  version "0.2.0"\n'
          '  version "0.1.0"\n',
        )),
        isNull,
      );
    });
  });

  group('the tap update', () {
    late Directory scratch;
    setUp(() => scratch = Directory.systemTemp.createTempSync('rk-tap-'));
    tearDown(() => scratch.deleteSync(recursive: true));

    /// A tap over scripted git, where the clone materialises [inTap] the way
    /// a real clone would.
    (HomebrewTap, RecordingTools) tap({
      Map<String, String> inTap = const {},
      bool pushRejected = false,
    }) {
      final checkout = '${scratch.path}/tap';
      final tools = RecordingTools(
        answers: (key) {
          if (key.startsWith('git push') && pushRejected) {
            return ToolResult(
              exitCode: 1,
              stdout: '',
              stderr: 'rejected: fetch first (non-fast-forward)',
            );
          }
          return null; // default ok
        },
        onRun: (key) {
          if (key.startsWith('git clone')) {
            Directory(checkout).createSync(recursive: true);
            inTap.forEach((path, contents) {
              File('$checkout/$path')
                ..parent.createSync(recursive: true)
                ..writeAsStringSync(contents);
            });
          }
        },
      );
      return (
        HomebrewTap(
            tools: tools, tap: 'owner/homebrew-tap', checkout: checkout),
        tools,
      );
    }

    test('a first-ever cask is written, staged, committed, and pushed',
        () async {
      // Two bugs lived here at once: the cask was written with `cat` and
      // no stdin — so the contents parameter was never used and the file
      // went out empty — and `git commit -a` never stages a new file, so
      // the empty write then read as "already current" and nothing pushed.
      final (tapUpdate, tools) = tap();
      final contents = render();
      final outcome = await tapUpdate.update(
        caskPath: 'Casks/keybay.rb',
        contents: contents,
        message: 'tool 1.0.0',
        authority: const HomebrewUpdateAuthority.absent(),
      );

      expect(outcome.ok, isTrue, reason: outcome.problem ?? '');
      expect(outcome.changed, isTrue);
      expect(
        File('${scratch.path}/tap/Casks/keybay.rb').readAsStringSync(),
        contents,
        reason: 'the pushed bytes are the contents rk rendered',
      );
      expect(
        tools.calls.any((c) => c == 'git add Casks/keybay.rb'),
        isTrue,
        reason: 'a new file must be staged by name',
      );
      expect(tools.calls.any((c) => c.startsWith('git commit')), isTrue);
      expect(tools.calls.any((c) => c.startsWith('git push')), isTrue);
    });

    test('an identical cask is unchanged, by bytes, with no git plumbing',
        () async {
      final (tapUpdate, tools) = tap(
        inTap: {'Casks/tool.rb': 'same\n'},
      );
      final outcome = await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'same\n',
        message: 'tool 1.0.0',
        authority: HomebrewUpdateAuthority.existing(utf8.encode('same\n')),
      );
      expect(outcome.ok, isTrue);
      expect(outcome.changed, isFalse);
      expect(
        tools.calls.where((c) => c.startsWith('git commit')),
        isEmpty,
      );
      expect(tools.calls.where((c) => c.startsWith('git push')), isEmpty);
    });

    test('a rejected push is the compare-and-swap failing, and says so',
        () async {
      final (tapUpdate, _) = tap(pushRejected: true);
      final outcome = await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'new\n',
        message: 'tool 1.0.0',
        authority: const HomebrewUpdateAuthority.absent(),
      );
      expect(outcome.ok, isFalse);
      expect(outcome.problem, contains('the tap moved'));
      expect(outcome.problem, contains('re-running reads it fresh'));
    });

    test('a push that fails for any other reason does not blame a mover',
        () async {
      // Auth failures and unreachable remotes wearing compare-and-swap
      // prose send the operator hunting for a concurrent writer that does
      // not exist.
      final checkout = '${scratch.path}/tap';
      final tools = RecordingTools(
        answers: (key) => key.startsWith('git push')
            ? ToolResult(
                exitCode: 1,
                stdout: '',
                stderr: 'fatal: could not read Username\n'
                    'remote: Support for password authentication was removed',
              )
            : null,
        onRun: (key) {
          if (key.startsWith('git clone')) {
            Directory(checkout).createSync(recursive: true);
          }
        },
      );
      final outcome = await HomebrewTap(
        tools: tools,
        tap: 'owner/homebrew-tap',
        checkout: checkout,
      ).update(
        caskPath: 'Casks/tool.rb',
        contents: 'new\n',
        message: 'tool 1.0.0',
        authority: const HomebrewUpdateAuthority.absent(),
      );
      expect(outcome.ok, isFalse);
      expect(outcome.problem, contains('the push failed'));
      expect(outcome.problem, isNot(contains('the tap moved')));
      // A lostTrack push is the least reproducible failure rk has: git's
      // second line is the one that says what to do about it.
      expect(
        outcome.transcript,
        contains('Support for password authentication was removed'),
      );
    });

    test('same length, different bytes, is still a change', () async {
      // Version bumps are frequently same-length (0.1.0 → 0.2.0); a
      // length-only comparison would decide "unchanged" and push nothing,
      // every run, forever.
      final (tapUpdate, tools) = tap(
        inTap: {'Casks/tool.rb': 'version "0.1.0"\n'},
      );
      final outcome = await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'version "0.2.0"\n',
        message: 'tool 0.2.0',
        authority: HomebrewUpdateAuthority.existing(
          utf8.encode('version "0.1.0"\n'),
        ),
      );
      expect(outcome.ok, isTrue);
      expect(outcome.changed, isTrue);
      expect(tools.calls.any((c) => c.startsWith('git push')), isTrue);
    });

    test('a stale checkout from an interrupted run is discarded first',
        () async {
      File('${scratch.path}/tap/Casks/stale.rb')
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('stale');

      final (tapUpdate, tools) = tap();
      await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'new\n',
        message: 'tool 1.0.0',
        authority: const HomebrewUpdateAuthority.absent(),
      );
      expect(
        File('${scratch.path}/tap/Casks/stale.rb').existsSync(),
        isFalse,
        reason: 'the compare-and-swap only means anything against a clone '
            'made now',
      );
      expect(tools.calls.any((c) => c.startsWith('git clone')), isTrue);
    });

    test('a hand edit between inspection and clone is not overwritten',
        () async {
      final observed = utf8.encode('version "0.1.0"\nsha256 "old"\n');
      final (tapUpdate, tools) = tap(
        inTap: {
          'Casks/tool.rb': 'version "0.1.0"\nsha256 "hand-edit"\n',
        },
      );

      final outcome = await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'version "0.2.0"\nsha256 "new"\n',
        message: 'tool 0.2.0',
        authority: HomebrewUpdateAuthority.existing(observed),
      );

      expect(outcome.ok, isFalse);
      expect(outcome.problem, contains('changed after rk inspected it'));
      expect(
        File('${scratch.path}/tap/Casks/tool.rb').readAsStringSync(),
        'version "0.1.0"\nsha256 "hand-edit"\n',
      );
      expect(tools.calls.where((c) => c.startsWith('git add')), isEmpty);
      expect(tools.calls.where((c) => c.startsWith('git push')), isEmpty);
    });

    test('a newer cask between inspection and clone is not overwritten',
        () async {
      final observed = utf8.encode('version "0.1.0"\nsha256 "old"\n');
      final (tapUpdate, tools) = tap(
        inTap: {
          'Casks/tool.rb': 'version "0.3.0"\nsha256 "newer"\n',
        },
      );

      final outcome = await tapUpdate.update(
        caskPath: 'Casks/tool.rb',
        contents: 'version "0.2.0"\nsha256 "new"\n',
        message: 'tool 0.2.0',
        authority: HomebrewUpdateAuthority.existing(observed),
      );

      expect(outcome.ok, isFalse);
      expect(outcome.problem, contains('changed after rk inspected it'));
      expect(
        File('${scratch.path}/tap/Casks/tool.rb').readAsStringSync(),
        'version "0.3.0"\nsha256 "newer"\n',
      );
      expect(tools.calls.where((c) => c.startsWith('git add')), isEmpty);
      expect(tools.calls.where((c) => c.startsWith('git push')), isEmpty);
    });
  });
}
