import 'package:rk/src/destinations/homebrew.dart';
import 'package:test/test.dart';

const _assets = {
  'macos-arm64': PlatformAsset(
    name: 'keybay-0.2.0-macos-arm64.tar.gz',
    sha256: 'aaaa',
  ),
  'linux-x64': PlatformAsset(
    name: 'keybay-0.2.0-linux-x64.tar.gz',
    sha256: 'bbbb',
  ),
  'linux-arm64': PlatformAsset(
    name: 'keybay-0.2.0-linux-arm64.tar.gz',
    sha256: 'cccc',
  ),
};

String render({Map<String, PlatformAsset> assets = _assets}) =>
    HomebrewFormula.render(
      className: 'Keybay',
      description: 'Secret storage for Dart',
      homepage: 'https://github.com/danReynolds/keybay',
      version: '0.2.0',
      repository: 'danReynolds/keybay',
      tag: 'keybay_cli-v0.2.0',
      assets: assets,
      executable: 'keybay',
    );

void main() {
  test('points at the release that produced the assets', () {
    final formula = render();
    expect(
      formula,
      contains('https://github.com/danReynolds/keybay/releases/download/'
          'keybay_cli-v0.2.0/keybay-0.2.0-macos-arm64.tar.gz'),
    );
    expect(formula, contains('sha256 "aaaa"'));
  });

  test('separates macOS and Linux, and Linux by architecture', () {
    final formula = render();
    expect(formula, contains('on_macos do'));
    expect(formula, contains('on_linux do'));
    expect(formula, contains('on_intel do'));
    expect(formula, contains('on_arm do'));
  });

  test('omits a platform the release does not ship', () {
    final formula = render(assets: {'macos-arm64': _assets['macos-arm64']!});
    expect(formula, contains('on_macos do'));
    expect(formula, isNot(contains('on_linux do')));
  });

  test('the test block checks the version the formula claims', () {
    expect(
      render(),
      contains('assert_match version.to_s, '
          'shell_output("#{bin}/keybay --version")'),
    );
  });

  test('says it is generated, and what editing it costs', () {
    final formula = render();
    expect(formula, contains('Generated by rk'));
    expect(formula, contains('next release stop'));
  });

  test('a quote cannot escape into the Ruby', () {
    final formula = HomebrewFormula.render(
      className: 'Keybay',
      description: 'A "quoted" description',
      homepage: 'https://example.com',
      version: '1.0.0',
      repository: 'a/b',
      tag: 'v1.0.0',
      assets: const {},
      executable: 'keybay',
    );
    expect(formula, contains('desc "A quoted description"'));
  });

  group('class names follow Homebrew\'s convention', () {
    test('a simple name', () {
      expect(HomebrewFormula.classNameFor('keybay'), 'Keybay');
    });
    test('an underscored name', () {
      expect(HomebrewFormula.classNameFor('keybay_cli'), 'KeybayCli');
    });
    test('a hyphenated name', () {
      expect(HomebrewFormula.classNameFor('my-tool'), 'MyTool');
    });
  });
}
