import 'dart:convert';
import 'dart:io';

import 'package:rk/src/engine/tools.dart';

/// Stands in for `dart pub deps --json` run in [workingDirectory], the way
/// the pub.dev stage runs it in its mirror of the source snapshot.
///
/// Like Pub, it leaves its records behind: the lockfile at the resolution
/// root, marking [overridden] packages as a dependency override replaced
/// them, and in the package a pointer to that root. It prints [graph], or
/// by default the package alone with no dependencies.
ToolResult pubDepsIn(
  String workingDirectory, {
  String? graph,
  Set<String> overridden = const {},
}) {
  final root = _resolutionRoot(workingDirectory);
  File('$root/.dart_tool/package_config.json')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('{"configVersion": 2, "packages": []}\n');
  File('$root/pubspec.lock').writeAsStringSync(_lockfile(overridden));
  final depth = workingDirectory.length > root.length
      ? workingDirectory.substring(root.length + 1).split('/').length
      : 0;
  File('$workingDirectory/.dart_tool/pub/workspace_ref.json')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
      '${jsonEncode({'workspaceRoot': List.filled(depth + 2, '..').join('/')})}\n',
    );
  return ToolResult(
    exitCode: 0,
    stdout: graph ?? _packageAlone(workingDirectory),
    stderr: '',
  );
}

/// Stands for `dart pub get` run in [workingDirectory]: resolves as
/// [pubDepsIn] does, and reports each of the [overridden] packages with the
/// `!` line Pub prints for an override it applied.
ToolResult pubGetIn(
  String workingDirectory, {
  Set<String> overridden = const {},
}) {
  pubDepsIn(workingDirectory, overridden: overridden);
  return ToolResult(
    exitCode: 0,
    stdout: [
      'Resolving dependencies...',
      for (final name in overridden)
        '! $name 9.9.9 from path ../$name (overridden)',
      'Got dependencies!',
      '',
    ].join('\n'),
    stderr: '',
  );
}

/// The ancestor a `resolution: workspace` package resolves at: the nearest
/// one declaring `workspace:`, followed up while that one is a member too.
String _resolutionRoot(String directory) {
  var root = directory;
  while (_pubspec(
    root,
  ).contains(RegExp(r'^resolution: workspace', multiLine: true))) {
    var dir = root;
    do {
      dir = File(dir).parent.path;
    } while (dir.length > 1 &&
        !_pubspec(dir).contains(RegExp(r'^workspace:', multiLine: true)));
    if (dir.length <= 1) return root;
    root = dir;
  }
  return root;
}

String _pubspec(String directory) {
  final file = File('$directory/pubspec.yaml');
  return file.existsSync() ? file.readAsStringSync() : '';
}

String _lockfile(Set<String> overridden) {
  if (overridden.isEmpty) return '# Generated by pub\npackages: {}\n';
  return [
    '# Generated by pub',
    'packages:',
    for (final name in overridden) ...[
      '  $name:',
      '    dependency: "direct overridden"',
      '    description:',
      '      path: "../$name"',
      '      relative: true',
      '    source: path',
      '    version: "9.9.9"',
    ],
    '',
  ].join('\n');
}

String _packageAlone(String directory) {
  final name = RegExp(
    r'^name:\s*(\S+)',
    multiLine: true,
  ).firstMatch(_pubspec(directory))?.group(1);
  return jsonEncode({
    'root': name,
    'packages': [
      {
        'name': name,
        'kind': 'root',
        'source': 'root',
        'dependencies': <String>[],
        'directDependencies': <String>[],
        'devDependencies': <String>[],
      },
    ],
  });
}
