schema = 2

[release.framework]
tag = "framework-v{version}"
publish = ["git-tag"]

[[release.framework.project]]
path = "packages/top"
publish = ["pub.dev"]

[[release.framework.project]]
path = "packages/middle"
publish = ["pub.dev"]

[[release.framework.project]]
path = "packages/base"
publish = ["pub.dev"]
