import 'dart:convert';
import 'dart:io';

import '../destinations/homebrew.dart';
import '../engine/assets.dart';
import '../engine/checklist.dart';
import '../engine/diagnostic.dart';
import '../engine/publish_target.dart';
import '../engine/producers.dart';
import '../engine/resolve.dart';
import '../engine/stage_contract.dart';
import '../engine/stage_inspection.dart';
import '../engine/stage_receipt.dart';
import '../engine/targets.dart';
import '../engine/verdict.dart';
import '../output/output.dart';
import '../transforms/digest.dart';
import 'published_release_evidence.dart';
import 'target_module.dart';

final class HomebrewTargetModule extends TargetModule {
  const HomebrewTargetModule();

  @override
  PublishTarget get target => PublishTarget.homebrew;

  @override
  StepKind get stepKind => StepKind.publishFormula;

  @override
  Future<bool> preflight(
    TargetReadinessContext context,
    ResolvedUnit unit,
  ) async =>
      true;

  @override
  Future<bool> acquireSession(
    TargetReadinessContext context,
    ResolvedUnit unit,
    List<TargetExpectation> targets,
  ) async =>
      true;

  @override
  TargetExpectation expectation({
    required ResolvedUnit unit,
    required Step step,
    String? repository,
  }) {
    final project = unit.project(step.project!);
    final tap = repository == null ? unit.homebrewTap : unit.tapFor(repository);
    return TargetExpectation(
      label: tap == null ? 'Homebrew' : 'Homebrew · $tap',
      kindLabel: 'Homebrew',
      identity: tap ?? 'no tap configured',
      coordinate: tap == null
          ? 'Formula/${project.executable}.rb'
          : '$tap/Formula/${project.executable}.rb',
      targetVersion: project.version.canonical,
      step: step,
      project: project,
      artifacts: [ReleaseAssets.formulaName(project.executable!)],
      uses: '${ReleaseAssets.formulaName(project.executable!)} bound in the '
          'release manifest',
      exactComparisonNeedsStage: true,
    );
  }

  @override
  Future<Inspection> inspectExact(
    TargetReadContext context,
    ResolvedUnit unit,
    TargetExpectation target,
  ) async {
    final tag = requiredTargetTag(unit, PublishTarget.homebrew);
    final tools = context.tools;
    if (tools == null) {
      return const Inspection.unknown('no tools to read the tap with');
    }
    final repository = context.repository;
    if (repository == null) {
      return const Inspection.unknown('no origin remote to ask');
    }
    final tap = unit.tapFor(repository);
    final project = target.project!;
    final executable = project.executable!;
    final stage = context.reusableStage(unit);
    final name = ReleaseAssets.formulaName(executable);
    final stagedPath = ReleaseAssets.formulaPath(project);
    List<int>? expectedBytes;
    String? expectedSha256;
    if (stage != null) {
      final expected = File(stage.directory.resolve(stagedPath));
      if (!expected.existsSync()) {
        return Inspection.conflict('the completed stage has no $name');
      }
      expectedBytes = expected.readAsBytesSync();
    } else if (context.git.hasTag(tag)) {
      final current =
          await PublishedReleaseEvidence(context).currentDestinationBinding(
        unit,
        target: PublishTarget.homebrew,
        project: project.name,
        coordinate: tap,
        path: 'Formula/$executable.rb',
      );
      if (current.inspection.verdict == Verdict.conflict ||
          current.inspection.verdict == Verdict.unknown) {
        return current.inspection;
      }
      final binding = current.binding!;
      if (binding.type != 'formula' || binding.mediaType != 'text/x-ruby') {
        return Inspection.conflict(
          'the release manifest binds the Homebrew destination with the '
          'wrong artifact type',
          evidence: {
            'type': binding.type,
            'media type': binding.mediaType,
          },
        );
      }
      expectedSha256 = binding.sha256;
    }

    return HomebrewTarget(
      tools: tools,
      tap: tap,
      workingDirectory: context.git.root,
    ).inspect(
      formulaPath: 'Formula/$executable.rb',
      expectedBytes: expectedBytes,
      expectedSha256: expectedSha256,
      inspectEarlierRelease: (bytes) =>
          _inspectEarlierFormula(context, unit, target, tap, bytes),
    );
  }

  Future<Inspection> _inspectEarlierFormula(
    TargetReadContext context,
    ResolvedUnit unit,
    TargetExpectation target,
    String tap,
    List<int> publicBytes,
  ) async {
    final pattern = requiredTargetTagPattern(unit, PublishTarget.homebrew);
    final version = HomebrewFormula.versionIn(publicBytes);
    if (version == null) {
      return const Inspection.conflict(
        'the public formula is not generated by rk with one canonical version',
      );
    }
    if (version >= unit.version) {
      return Inspection.conflict(
        'the public formula claims ${version.canonical}, not an earlier '
        'release than ${unit.version}',
      );
    }
    final project = target.project!;
    final path = 'Formula/${project.executable!}.rb';
    final read =
        await PublishedReleaseEvidence(context).historicalDestinationBinding(
      unit,
      version,
      target: PublishTarget.homebrew,
      project: project,
      coordinate: tap,
      path: path,
    );
    if (!read.inspection.isExact) return read.inspection;
    final binding = read.binding!;
    if (binding.type != 'formula' ||
        binding.mediaType != 'text/x-ruby' ||
        binding.sha256 != Sha256.hex(publicBytes)) {
      final tag = pattern.replaceAll('{version}', version.canonical);
      return Inspection.conflict(
        'the tap formula differs from the formula bound to $tag',
      );
    }
    final tag = pattern.replaceAll('{version}', version.canonical);
    return Inspection.exact(
      detail: 'matches the manifest-bound formula from $tag',
      evidence: {'version': version.canonical},
    );
  }

  @override
  String conflictRemedy(
    ResolvedUnit unit,
    TargetExpectation target,
  ) =>
      'restore the formula to the exact release bytes it is meant to '
      'reference, or advance the source version intentionally; then '
      'run rk status ${unit.name} again';

  @override
  Future<TargetActOutcome> act(
    TargetReleaseContext context,
    ResolvedUnit unit,
    TargetExpectation target,
    Inspection inspected,
  ) async {
    final repository = context.repository;
    if (repository == null) {
      return TargetActOutcome(
        ok: false,
        diagnostic: Diagnostic(
          code: 'RK-GIT-002',
          message: 'homebrew needs an origin remote, and this repository '
              'has none',
          remedy: 'rk publishes what others can fetch, and reads back what it '
              'published. git remote add origin <url>, then git push -u '
              'origin ${context.git.branch ?? 'main'}',
        ),
      );
    }
    final authority = inspected.authority;
    if (authority is! HomebrewUpdateAuthority) {
      return const TargetActOutcome(
        ok: false,
        problem: 'the formula update has no exact public base; re-run so rk '
            'can inspect the tap before updating it',
      );
    }
    final project = target.project!;
    final executable = project.executable!;
    final formula =
        context.workspace.readBytes(ReleaseAssets.formulaPath(project));
    if (formula == null) {
      return TargetActOutcome(
        ok: false,
        problem: 'the workspace has no '
            '${ReleaseAssets.formulaName(executable)}; the staging phase '
            'renders it — re-running runs it',
      );
    }
    final Directory scratch;
    try {
      scratch = Directory.systemTemp.createTempSync('rk-tap-');
    } on FileSystemException catch (error) {
      return TargetActOutcome(
        ok: false,
        problem: 'a temporary checkout could not be created: $error',
      );
    }
    final outcome = await HomebrewTap(
      tools: context.tools,
      tap: unit.tapFor(repository),
      checkout: '${scratch.path}/tap',
    ).update(
      formulaPath: 'Formula/$executable.rb',
      contents: utf8.decode(formula),
      message: '$executable ${project.version}',
      authority: authority,
    );
    try {
      scratch.deleteSync(recursive: true);
    } on FileSystemException {
      // Public truth, not scratch cleanup, decides the target.
    }
    return TargetActOutcome(
      ok: outcome.ok,
      problem: outcome.problem,
      mayHaveActed: outcome.mayHaveActed,
    );
  }

  @override
  Future<TargetFailure> classifyFailure(
    TargetReleaseContext context,
    ResolvedUnit unit,
    TargetExpectation target,
    Inspection state,
    TargetActOutcome act, {
    required bool actedBefore,
  }) async {
    final code = switch (state.verdict) {
      Verdict.unknown => 'RK-BREW-002',
      Verdict.conflict => 'RK-BREW-003',
      Verdict.absent || Verdict.exact => 'RK-BREW-001',
    };
    final message = switch (state.verdict) {
      Verdict.unknown => 'the tap was updated and could not be read back',
      Verdict.conflict => 'the public tap does not hold what rk pushed',
      Verdict.absent || Verdict.exact => 'the tap formula was not updated',
    };
    final details = <String>[
      if (act.diagnostic?.remedy != null) act.diagnostic!.remedy!,
      if (act.problem != null) act.problem!,
      if (state.detail != null) state.detail!,
      ...state.evidence.entries.map((entry) => '${entry.key}: ${entry.value}'),
    ];
    final halt = state.verdict == Verdict.conflict
        ? HaltKind.stoppedPartway
        : act.mayHaveActed || state.verdict == Verdict.unknown
            ? HaltKind.lostTrack
            : actedBefore
                ? HaltKind.stoppedPartway
                : HaltKind.beforeActing;
    return TargetFailure(
      diagnostic: Diagnostic(
        code: code,
        message: message,
        remedy: details.isEmpty
            ? 're-run; the shared destination inspection will classify the '
                'public target before any retry'
            : details.join('\n'),
      ),
      halt: halt,
    );
  }

  @override
  TargetStage stage({
    required ResolvedUnit unit,
    required TargetExpectation target,
  }) {
    final tag = requiredTargetTag(unit, PublishTarget.homebrew);
    final project = target.project!;
    final executable = project.executable!;
    final archives = {
      for (final platform in project.binaryPlatforms)
        ReleaseAssets.archivePath(project, platform),
    };
    final contract = StageContributionContract(
      phase: StageContributionPhase.afterArtifacts,
      step: StageStepContract(
        'homebrew-formula:${project.name}',
        inputs: archives,
        outputs: {ReleaseAssets.formulaPath(project): 'formula'},
        validate: (context, step) {
          final repository = context.repository;
          if (repository == null) {
            return const [
              StageIssue(
                StageIssueKind.invalidStructure,
                'homebrew-formula has no repository identity',
                path: 'stage.json',
              ),
            ];
          }
          final publicArchives = {
            for (final platform in project.binaryPlatforms)
              platform: PlatformAsset(
                name: context.receipt.steps
                    .singleWhere((item) =>
                        item.name == archiveReceiptName(project.name, platform))
                    .outputs
                    .single
                    .path,
                sha256: context.receipt.steps
                    .singleWhere((item) =>
                        item.name == archiveReceiptName(project.name, platform))
                    .outputs
                    .single
                    .sha256,
              ),
          };
          final expected = HomebrewFormula.render(
            className: HomebrewFormula.classNameFor(executable),
            description: 'Released by rk',
            homepage: 'https://github.com/$repository',
            version: project.version.canonical,
            repository: repository,
            tag: tag,
            executable: executable,
            assets: publicArchives,
          );
          final actual = File(
            context.stage.resolve(ReleaseAssets.formulaPath(project)),
          );
          if (actual.existsSync() && actual.readAsStringSync() == expected) {
            return const [];
          }
          return const [
            StageIssue(
              StageIssueKind.invalidStructure,
              'homebrew-formula does not match the staged archives',
              path: 'stage.json',
            ),
          ];
        },
      ),
    );
    return TargetStage(
      target: target,
      contract: contract,
      prepare: (context) => _prepareStage(context, unit, target),
    );
  }

  Future<StageStep?> _prepareStage(
    TargetStageContext context,
    ResolvedUnit unit,
    TargetExpectation target,
  ) async {
    final tag = requiredTargetTag(unit, PublishTarget.homebrew);
    final receiptName = context.contract.step.name;
    final repository = context.repository;
    if (repository == null) {
      context.output.problem(
        Diagnostic(
          code: 'RK-GIT-002',
          message: 'homebrew needs an origin remote, and this repository '
              'has none',
          remedy: 'rk publishes what others can fetch, and reads back what it '
              'published. git remote add origin <url>, then git push -u '
              'origin ${context.git.branch ?? 'main'}',
        ),
      );
      context.output.halt(HaltKind.beforeActing);
      return null;
    }

    final project = target.project!;
    final archives = <String, StageArtifact>{};
    for (final platform in project.binaryPlatforms) {
      final record = context.progress
          .where(
              (step) => step.name == archiveReceiptName(project.name, platform))
          .firstOrNull;
      final artifact = record?.outputs
          .where((output) => output.type == 'archive')
          .firstOrNull;
      if (artifact == null) {
        context.output.problem(
          Diagnostic(
            code: 'RK-WORK-001',
            message: 'the workspace has no archive for $platform',
            remedy: 'the archive step produces it — re-running runs it',
          ),
          unit: unit.name,
        );
        return null;
      }
      archives[platform] = artifact;
    }
    context.output.report.acted = true;
    final executable = project.executable!;
    final contents = HomebrewFormula.render(
      className: HomebrewFormula.classNameFor(executable),
      description: 'Released by rk',
      homepage: 'https://github.com/$repository',
      version: project.version.canonical,
      repository: repository,
      tag: tag,
      executable: executable,
      assets: {
        for (final MapEntry(key: platform, value: archive) in archives.entries)
          platform: PlatformAsset(
            name: archive.path,
            sha256: archive.sha256,
          ),
      },
    );
    context.workspace.write(
      ReleaseAssets.formulaPath(project),
      utf8.encode(contents),
    );
    return StageStep(
      name: receiptName,
      inputs: [
        for (final archive in archives.values) StageInput.artifact(archive),
      ],
      outputs: [
        StageArtifact.capture(
          stage: context.stage.directory,
          path: ReleaseAssets.formulaPath(project),
          type: 'formula',
        ),
      ],
    );
  }
}
