import 'dart:convert';
import 'dart:io';

import 'model.dart';

/// Dart 3.10–3.12 discovers hooks from the invoking directory. Prepare assets
/// there, then run the original script in its own isolate with the caller cwd.
/// The child keeps Platform.script, argument handling and ordinary stdio.
String? localBootstrap(
  ExecutableProject project,
  String command,
  String entry,
) {
  var directory = Directory(project.directory);
  File? config;
  while (true) {
    final candidate = File('${directory.path}/.dart_tool/package_config.json');
    if (candidate.existsSync()) {
      config = candidate;
      break;
    }
    if (directory.path == project.root ||
        directory.parent.path == directory.path) {
      return null;
    }
    directory = directory.parent;
  }
  final json = jsonDecode(config.readAsStringSync()) as Map<String, dynamic>;
  final packages = (json['packages'] as List).cast<Map<String, dynamic>>();
  final hasHooks = packages.any((package) {
    final root = Directory.fromUri(
      config!.uri.resolve(package['rootUri'] as String),
    ).uri;
    return File.fromUri(root.resolve('hook/build.dart')).existsSync();
  });
  if (!hasHooks) return null;
  final path = '${project.directory}/.dart_tool/rk-local/$command.dart';
  final script = File(path)..parent.createSync(recursive: true);
  String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  script.writeAsStringSync('''
// Generated by rk use local. The application's original entrypoint is retained.
import 'dart:io';
import 'dart:isolate';
Future<void> main(List<String> args) async {
  Directory.current = args.first;
  final events = ReceivePort();
  try {
    await Isolate.spawnUri(
      Uri.parse(${literal(File(entry).uri.toString())}),
      args.sublist(1), null,
      packageConfig: Uri.parse(${literal(config.uri.toString())}),
      onExit: events.sendPort, onError: events.sendPort, errorsAreFatal: true,
    );
    await for (final event in events) {
      if (event == null) break;
      stderr.writeln((event as List).join('\\n'));
      exitCode = 255;
    }
  } finally {
    events.close();
  }
}
''');
  return path;
}
