import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';
import 'package:rk/src/transforms/digest.dart';
import 'package:yaml/yaml.dart';

/// A credential-free registry for native Pub integration fixtures.
/// Every unexpected request fails; it has no upload endpoint or remote fallback.
final class NativePubFixture {
  NativePubFixture._(this.directory, this.server);

  final Directory directory;
  final HttpServer server;
  final Map<String, Map<String, _Package>> _packages = {};
  final List<String> requests = [];
  String archiveQuery = '';
  String? archiveRedirect;
  final Map<String, int> packageStatus = {};
  final Set<Process> _children = {};

  String get url => 'http://127.0.0.1:${server.port}';
  String get dart =>
      Platform.environment['RK_NATIVE_DART'] ?? Platform.resolvedExecutable;

  static Future<NativePubFixture> create() async {
    final directory = Directory.systemTemp.createTempSync('rk-native-pub-');
    final git = await Process.run('git', ['init', '--quiet', directory.path]);
    if (git.exitCode != 0) {
      directory.deleteSync(recursive: true);
      throw StateError('cannot initialize native fixture: ${git.stderr}');
    }
    final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    final fixture = NativePubFixture._(directory, server);
    server.listen(fixture._respond);
    return fixture;
  }

  Future<void> close() async {
    for (final child in _children) {
      child.kill(ProcessSignal.sigkill);
    }
    await server.close(force: true);
    directory.deleteSync(recursive: true);
  }

  Directory package(
    String relative,
    String name,
    String version, {
    String dependencies = '',
    String development = '',
    String sdk = '^3.10.4',
    String library = 'const value = 42;\n',
    Map<String, String> extra = const {},
  }) {
    final root = Directory('${directory.path}/$relative')
      ..createSync(recursive: true);
    final files = {
      'pubspec.yaml':
          'name: $name\nversion: $version\n'
          'description: Native RK dependency staging integration fixture.\n'
          'environment:\n  sdk: $sdk\n'
          '${dependencies.isEmpty ? '' : 'dependencies:\n$dependencies'}'
          '${development.isEmpty ? '' : 'dev_dependencies:\n$development'}',
      'README.md': '# $name\nNative staging fixture.\n',
      'CHANGELOG.md': '## $version\n\nNative staging fixture.\n',
      'LICENSE': 'Fixture provided for testing.\n',
      'lib/$name.dart': library,
      ...extra,
    };
    for (final entry in files.entries) {
      final file = File('${root.path}/${entry.key}');
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
    }
    return root;
  }

  /// Registry fixtures need not be generated by the operation under test.
  /// The *staged provider* is built with Pub's native --to-archive command.
  void host(Directory root, {Map<String, String> sources = const {}}) {
    final manifest =
        _plain(loadYaml(File('${root.path}/pubspec.yaml').readAsStringSync()))
            as Map<String, Object?>;
    final archive = Archive();
    for (final entity in root.listSync(recursive: true)) {
      if (entity is! File) continue;
      final relative = entity.path.substring(root.path.length + 1);
      archive.addFile(ArchiveFile.bytes(relative, entity.readAsBytesSync()));
    }
    final bytes = GZipEncoder().encode(TarEncoder().encode(archive));
    final name = manifest['name']! as String;
    final version = manifest['version']! as String;
    (_packages[name] ??= {})[version] = _Package(
      remapSources(manifest, sources),
      bytes,
    );
  }

  /// Deliberately contains no runtime payload. These packages are only native
  /// solver metadata and cannot be used for packaging or compilation.
  void discover(Directory root, Map<String, String> sources) {
    final manifest = remapSources(
      _plain(loadYaml(File('${root.path}/pubspec.yaml').readAsStringSync()))
          as Map<String, Object?>,
      sources,
    );
    final archive = Archive()
      ..addFile(ArchiveFile.string('pubspec.yaml', jsonEncode(manifest)));
    final bytes = GZipEncoder().encode(TarEncoder().encode(archive));
    (_packages[manifest['name'] as String] ??= {})[manifest['version']
        as String] = _Package(
      manifest,
      bytes,
    );
  }

  void rewriteSources(Directory root, Map<String, String> sources) {
    final file = File('${root.path}/pubspec.yaml');
    file.writeAsStringSync(
      jsonEncode(
        remapSources(
          _plain(loadYaml(file.readAsStringSync())) as Map<String, Object?>,
          sources,
        ),
      ),
    );
  }

  Map<String, Object?> remapSources(
    Map<String, Object?> manifest,
    Map<String, String> sources,
  ) {
    if (sources.isEmpty) return manifest;
    return {
      ...manifest,
      for (final section in ['dependencies', 'dev_dependencies'])
        if (manifest[section] case final Map dependencies)
          section: {
            for (final entry in dependencies.entries)
              entry.key: _remapDependency(entry.value, sources),
          },
    };
  }

  Object? _remapDependency(Object? dependency, Map<String, String> sources) {
    if (dependency is Map &&
        ['path', 'git', 'sdk'].any(dependency.containsKey)) {
      return dependency;
    }
    final details = dependency is Map
        ? {...dependency}
        : <Object?, Object?>{'version': dependency ?? 'any'};
    final hosted = details['hosted'];
    final original = hosted is Map ? hosted['url'] : hosted;
    final mapped = sources[original ?? 'default'];
    if (mapped == null) return dependency;
    return {
      ...details,
      'hosted': hosted is Map ? {...hosted, 'url': mapped} : mapped,
    };
  }

  File hostedArchive(String name, String version) =>
      File('${directory.path}/$name-$version.tar.gz')
        ..writeAsBytesSync(_packages[name]![version]!.bytes);

  Map<String, Object?> lock(Directory root) =>
      _plain(loadYaml(File('${root.path}/pubspec.lock').readAsStringSync()))
          as Map<String, Object?>;

  /// Native dependency relationships plus source identities. Discovery hashes
  /// identify metadata payloads, so real archive hashes are checked separately.
  Map<String, Object?> graph(
    Directory root, {
    Map<String, String> sources = const {},
  }) {
    final graph =
        jsonDecode(
              File(
                '${root.path}/.dart_tool/package_graph.json',
              ).readAsStringSync(),
            )
            as Map;
    final locked = lock(root)['packages'] as Map;
    return {
      for (final package in (graph['packages'] as List).cast<Map>())
        package['name'] as String: {
          ...package,
          if (locked[package['name']] case final Map entry)
            'source': entry['source'],
          if (locked[package['name']] case {
            'description': {'url': final String url},
          })
            'url': sources[url] ?? url,
        },
    };
  }

  Directory extract(File archive, String relative) {
    final destination = Directory('${directory.path}/$relative')
      ..createSync(recursive: true);
    final contents = TarDecoder().decodeBytes(
      GZipDecoder().decodeBytes(archive.readAsBytesSync()),
    );
    for (final entry in contents) {
      if (!entry.isFile) continue;
      final file = File('${destination.path}/${entry.name}');
      file.parent.createSync(recursive: true);
      file.writeAsBytesSync(entry.content);
    }
    return destination;
  }

  void workspace(String relative, List<Directory> members) {
    final root = Directory('${directory.path}/$relative')
      ..createSync(recursive: true);
    File('${root.path}/pubspec.yaml').writeAsStringSync(
      'name: rk_fixture_workspace\npublish_to: none\n'
      'environment:\n  sdk: ^3.10.4\nworkspace:\n'
      '${members.map((member) => '  - ${member.path.substring(root.path.length + 1)}\n').join()}',
    );
    for (final member in members) {
      File(
        '${member.path}/pubspec_overrides.yaml',
      ).writeAsStringSync('resolution: workspace\n');
    }
  }

  Future<ProcessResult> run(
    Directory cwd,
    List<String> arguments, {
    String cache = 'cache',
    String? hosted,
  }) async {
    final child = await Process.start(
      dart,
      ['--suppress-analytics', ...arguments],
      workingDirectory: cwd.path,
      environment: {
        'PUB_CACHE': '${directory.path}/$cache',
        'PUB_HOSTED_URL': hosted ?? url,
        'PUB_ENVIRONMENT': 'rk-native-fixture',
      },
    );
    _children.add(child);
    final stdout = child.stdout.transform(utf8.decoder).join();
    final stderr = child.stderr.transform(utf8.decoder).join();
    try {
      final code = await child.exitCode.timeout(
        const Duration(seconds: 90),
        onTimeout: () {
          child.kill(ProcessSignal.sigkill);
          throw StateError(
            'native fixture timed out: dart ${arguments.join(' ')}',
          );
        },
      );
      return ProcessResult(child.pid, code, await stdout, await stderr);
    } finally {
      _children.remove(child);
    }
  }

  Future<void> _respond(HttpRequest request) async {
    requests.add('${request.method} ${request.uri.path}');
    final path = request.uri.pathSegments;
    if (request.method != 'GET') {
      request.response.statusCode = HttpStatus.methodNotAllowed;
    } else if (path.length == 3 && path[0] == 'api' && path[1] == 'packages') {
      final packages = _packages[path[2]];
      if (packageStatus[path[2]] case final status?) {
        request.response.statusCode = status;
      } else if (packages == null) {
        request.response.statusCode = HttpStatus.notFound;
      } else {
        final versions = [
          for (final entry in packages.entries)
            {
              'version': entry.key,
              'pubspec': entry.value.manifest,
              'archive_url':
                  '$url/packages/${path[2]}-${entry.key}.tar.gz$archiveQuery',
              'archive_sha256': Sha256.hex(entry.value.bytes),
            },
        ];
        request.response.headers.contentType = ContentType.json;
        request.response.write(
          jsonEncode({
            'name': path[2],
            'latest': versions.last,
            'versions': versions,
          }),
        );
      }
    } else if (path.length == 2 && path[0] == 'packages') {
      if (archiveRedirect case final location?) {
        request.response.statusCode = HttpStatus.found;
        request.response.headers.set(HttpHeaders.locationHeader, location);
        await request.response.close();
        return;
      }
      _Package? found;
      for (final package in _packages.entries) {
        for (final version in package.value.entries) {
          if (path[1] == '${package.key}-${version.key}.tar.gz') {
            found = version.value;
          }
        }
      }
      if (found == null) {
        request.response.statusCode = HttpStatus.notFound;
      } else {
        request.response.add(found.bytes);
      }
    } else {
      request.response.statusCode = HttpStatus.notFound;
    }
    await request.response.close();
  }
}

Object? _plain(Object? value) => switch (value) {
  Map() => {
    for (final entry in value.entries) '${entry.key}': _plain(entry.value),
  },
  List() => value.map(_plain).toList(),
  _ => value,
};

final class _Package {
  _Package(this.manifest, this.bytes);
  final Map<String, Object?> manifest;
  final List<int> bytes;
}
