schema = 2

[release.core]
tag = "core-v{version}"
path = "packages/core"
publish = ["git-tag", "pub.dev"]

[release.cli]
tag = "cli-v{version}"
path = "packages/cli"
publish = ["git-tag", "pub.dev"]
