import 'dart:convert';
import 'dart:io';

import '../engine/tools.dart';
import '../engine/verdict.dart';
import '../engine/version.dart';
import '../transforms/digest.dart';

/// Renders and publishes the formula that points at a release's assets.
///
/// A formula is executable Ruby, so rk emits one fixed structure from
/// validated values and never accepts a template. The formula points at
/// published assets, so it moves only after the release is public — and it is
/// a mutable pointer, so it moves forward under compare-and-swap rather than
/// being overwritten.
class HomebrewFormula {
  /// Builds the formula text.
  ///
  /// Every value is either derived from the manifest or a digest of an asset
  /// rk produced; nothing here is interpolated from configuration.
  static String render({
    required String className,
    required String description,
    required String homepage,
    required String version,
    required String repository,
    required String tag,
    required Map<String, PlatformAsset> assets,
    required String executable,
  }) {
    final buffer = StringBuffer()
      ..writeln('# Generated by rk. Edits are overwritten and will make the')
      ..writeln('# next release stop, because rk compares this file to the')
      ..writeln('# release it names.')
      ..writeln('class $className < Formula')
      ..writeln('  desc "${_escape(description)}"')
      ..writeln('  homepage "${_escape(homepage)}"')
      ..writeln('  version "$version"')
      ..writeln('  license :cannot_represent')
      ..writeln();

    final macArm = assets['macos-arm64'];
    if (macArm != null) {
      buffer
        ..writeln('  on_macos do')
        ..writeln('    on_arm do')
        ..writeln('      url "${_url(repository, tag, macArm.name)}"')
        ..writeln('      sha256 "${macArm.sha256}"')
        ..writeln('    end')
        ..writeln('  end')
        ..writeln();
    }

    final linuxX64 = assets['linux-x64'];
    final linuxArm = assets['linux-arm64'];
    if (linuxX64 != null || linuxArm != null) {
      buffer.writeln('  on_linux do');
      if (linuxX64 != null) {
        buffer
          ..writeln('    on_intel do')
          ..writeln('      url "${_url(repository, tag, linuxX64.name)}"')
          ..writeln('      sha256 "${linuxX64.sha256}"')
          ..writeln('    end');
      }
      if (linuxArm != null) {
        buffer
          ..writeln('    on_arm do')
          ..writeln('      url "${_url(repository, tag, linuxArm.name)}"')
          ..writeln('      sha256 "${linuxArm.sha256}"')
          ..writeln('    end');
      }
      buffer
        ..writeln('  end')
        ..writeln();
    }
    buffer
      ..writeln('  def install')
      ..writeln('    bin.install "$executable"')
      ..writeln('  end')
      ..writeln()
      ..writeln('  test do')
      ..writeln('    assert_match version.to_s, '
          'shell_output("#{bin}/$executable --version")')
      ..writeln('  end')
      ..writeln('end');

    return buffer.toString();
  }

  /// The Homebrew class name for a formula file.
  static String classNameFor(String executable) => executable
      .split(RegExp('[_-]'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join();

  /// The canonical version claimed by bytes produced by this renderer.
  ///
  /// This is only a coordinate locator. Callers still prove the complete
  /// bytes against the manifest bound into that version's tag before trusting
  /// it as an earlier release.
  static Version? versionIn(List<int> bytes) {
    final String source;
    try {
      source = utf8.decode(bytes);
    } on FormatException {
      return null;
    }
    if (!source.startsWith('# Generated by rk.')) return null;
    final matches = RegExp(r'^  version "([^"]+)"$', multiLine: true)
        .allMatches(source)
        .toList();
    if (matches.length != 1) return null;
    final raw = matches.single.group(1)!;
    final parsed = Version.tryParse(raw);
    return parsed != null && parsed.canonical == raw ? parsed : null;
  }

  static String _url(String repository, String tag, String asset) =>
      'https://github.com/$repository/releases/download/$tag/$asset';

  /// Values are derived, never interpolated, but a quote would still break the
  /// file — so one cannot appear.
  static String _escape(String value) => value.replaceAll('"', '');
}

class PlatformAsset {
  const PlatformAsset({required this.name, required this.sha256});
  final String name;
  final String sha256;
}

/// The exact public formula base an update was authorized against.
///
/// A missing formula and an existing zero-byte formula are different bases.
/// Existing bytes are represented by their digest so the authority is small
/// while still binding every byte observed by [HomebrewTarget.inspect].
class HomebrewUpdateAuthority {
  const HomebrewUpdateAuthority.absent() : sha256 = null;

  HomebrewUpdateAuthority.existing(List<int> bytes)
      : sha256 = Sha256.hex(bytes);

  final String? sha256;

  bool accepts(List<int>? bytes) {
    final expected = sha256;
    if (expected == null) return bytes == null;
    return bytes != null && Sha256.hex(bytes) == expected;
  }

  String mismatch(List<int>? bytes) {
    final expected = sha256 == null ? 'no formula' : 'sha256 $sha256';
    final actual = bytes == null ? 'no formula' : 'sha256 ${Sha256.hex(bytes)}';
    return 'expected $expected; the fresh tap has $actual';
  }
}

/// Reads the formula exactly as Homebrew users receive it.
///
/// A version substring is not proof: URLs or hashes can be hand-edited while
/// the version remains unchanged. An older formula is ordinary work only when
/// [inspectEarlierRelease] proves its full bytes came from an immutable older
/// release; every other difference is a conflict.
class HomebrewTarget {
  HomebrewTarget({
    required this.tools,
    required this.tap,
    this.workingDirectory,
  });

  final Tools tools;
  final String tap;
  final String? workingDirectory;

  Future<Inspection> inspect({
    required String formulaPath,
    required List<int>? expectedBytes,
    String? expectedSha256,
    Future<Inspection> Function(List<int> bytes)? inspectEarlierRelease,
  }) async {
    if (expectedBytes != null && expectedSha256 != null) {
      throw ArgumentError(
        'Homebrew inspection accepts expected bytes or a digest, not both',
      );
    }
    if (expectedSha256 != null &&
        !RegExp(r'^[0-9a-f]{64}$').hasMatch(expectedSha256)) {
      throw ArgumentError('expected formula digest is not lowercase SHA-256');
    }
    final result = await tools.run(
      'gh',
      ['api', 'repos/$tap/contents/$formulaPath'],
      workingDirectory: workingDirectory,
    );
    if (!result.ok) {
      if (result.summary.contains('(HTTP 404)')) {
        final readable = await tools.run(
          'gh',
          ['repo', 'view', tap, '--json', 'name'],
          workingDirectory: workingDirectory,
        );
        return readable.ok
            ? const Inspection.absent(
                detail: 'no formula in the tap yet',
                evidence: {'public formula': 'absent'},
                authority: HomebrewUpdateAuthority.absent(),
              )
            : Inspection.unknown(
                'the tap $tap could not be read, so rk cannot tell what '
                'users install',
              );
      }
      return Inspection.unknown('the tap could not be read: ${result.summary}');
    }

    final List<int> publicBytes;
    try {
      final decoded = jsonDecode(result.stdout);
      final content = decoded is Map ? decoded['content'] : null;
      if (content is! String) {
        return const Inspection.unknown(
          'the tap answered something unreadable',
        );
      }
      publicBytes = base64Decode(content.replaceAll(RegExp(r'\s'), ''));
    } on Object catch (error) {
      return Inspection.unknown(
          'the tap answered something unreadable: $error');
    }

    final publicSha256 = Sha256.hex(publicBytes);
    if ((expectedBytes != null && _sameBytes(publicBytes, expectedBytes)) ||
        (expectedSha256 != null && publicSha256 == expectedSha256)) {
      final version = HomebrewFormula.versionIn(publicBytes);
      return Inspection.exact(
        detail: 'formula bytes match the release',
        evidence: {
          'sha256': publicSha256,
          if (version != null) 'version': version.canonical,
        },
      );
    }

    if (inspectEarlierRelease != null) {
      final earlier = await inspectEarlierRelease(publicBytes);
      if (earlier.isExact) {
        final version = HomebrewFormula.versionIn(publicBytes);
        final authority = HomebrewUpdateAuthority.existing(publicBytes);
        return Inspection.absent(
          detail: 'the tap points at an earlier exact release',
          evidence: {
            if (version != null) 'version': version.canonical,
            'public sha256': authority.sha256!,
          },
          authority: authority,
        );
      }
      if (earlier.verdict == Verdict.unknown) {
        return Inspection.unknown(
          earlier.detail ?? 'the public formula could not be authenticated',
        );
      }
    }

    return Inspection.conflict(
      'the public formula is not an exact release formula',
      evidence: {
        if (expectedBytes != null) 'expected sha256': Sha256.hex(expectedBytes),
        if (expectedSha256 != null) 'expected sha256': expectedSha256,
        'public sha256': publicSha256,
      },
    );
  }

  static bool _sameBytes(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}

/// Moves a tap's formula forward, only from the state rk inspected.
class HomebrewTap {
  HomebrewTap({
    required this.tools,
    required this.tap,
    required this.checkout,
  });

  final Tools tools;

  /// `owner/homebrew-tap`.
  final String tap;

  /// Where the tap is cloned for this operation.
  final String checkout;

  /// Clones the tap, replaces the formula, and pushes — refusing if the
  /// remote moved under it, which is the compare-and-swap.
  ///
  /// The shared target inspection is the authorization read. The fresh clone
  /// must match that exact formula base, and a non-fast-forward rejection then
  /// catches movement after cloning.
  Future<TapOutcome> update({
    required String formulaPath,
    required String contents,
    required String message,
    required HomebrewUpdateAuthority authority,
  }) async {
    // A checkout left by an interrupted run is stale by definition; the
    // compare-and-swap only means anything against a clone made now.
    final stale = Directory(checkout);
    if (stale.existsSync()) stale.deleteSync(recursive: true);

    final cloned = await tools.run('git', [
      'clone',
      '--depth',
      '1',
      'https://github.com/$tap.git',
      checkout,
    ]);
    if (!cloned.ok) return TapOutcome.failed(cloned.summary);

    // The API inspection authorized one exact base. The fresh clone must
    // still contain that base before rk writes anything; the push then guards
    // the remaining clone-to-remote gap with Git's fast-forward rule.
    final file = File('$checkout/$formulaPath');
    final List<int>? existing;
    try {
      existing = file.existsSync() ? file.readAsBytesSync() : null;
    } on FileSystemException catch (error) {
      return TapOutcome.failed('the cloned formula could not be read: $error');
    }
    if (!authority.accepts(existing)) {
      return TapOutcome.failed(
        'the tap formula changed after rk inspected it; '
        '${authority.mismatch(existing)}. Re-run so rk can inspect the new '
        'public formula before updating it',
      );
    }

    // Unchanged is decided by bytes, before any git plumbing. The previous
    // version asked `git commit -a` to decide — which never stages a *new*
    // file, so a first-ever formula read as "already current" and nothing
    // was pushed. (It also wrote the file with `cat` and no stdin, so what
    // it committed was empty — [contents] was never used at all. Both are
    // why the tap step's test now asserts the pushed bytes.)
    final replacement = utf8.encode(contents);
    if (existing != null && HomebrewTarget._sameBytes(existing, replacement)) {
      return const TapOutcome.unchanged();
    }

    try {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(contents);
    } on FileSystemException catch (error) {
      return TapOutcome.failed('the formula could not be written: $error');
    }

    final added = await tools.run(
      'git',
      ['add', formulaPath],
      workingDirectory: checkout,
    );
    if (!added.ok) return TapOutcome.failed(added.summary);

    final committed = await tools.run(
      'git',
      ['commit', '-m', message],
      workingDirectory: checkout,
    );
    if (!committed.ok) return TapOutcome.failed(committed.summary);

    final pushed = await tools.run(
      'git',
      const ['push'],
      workingDirectory: checkout,
    );
    if (!pushed.ok) {
      // Only an actual rejection is the compare-and-swap failing; an auth
      // failure or an unreachable remote wearing "the tap moved" prose
      // would send the operator hunting for a concurrent writer that does
      // not exist.
      final said = pushed.summary.toLowerCase();
      final rejected = said.contains('non-fast-forward') ||
          said.contains('fetch first') ||
          said.contains('rejected');
      return rejected
          ? TapOutcome.failed(
              'the tap moved while rk was working — re-running reads it '
              'fresh: ${pushed.summary}',
            )
          : TapOutcome.lostTrack('the push failed: ${pushed.summary}');
    }
    return const TapOutcome.updated();
  }
}

class TapOutcome {
  const TapOutcome._(this.problem, this.changed, this.mayHaveActed);
  const TapOutcome.updated() : this._(null, true, true);
  const TapOutcome.unchanged() : this._(null, false, false);
  const TapOutcome.failed(String problem) : this._(problem, false, false);
  const TapOutcome.lostTrack(String problem) : this._(problem, false, true);

  final String? problem;
  final bool changed;
  final bool mayHaveActed;
  bool get ok => problem == null;
}
