import 'dart:convert';
import 'dart:io';

import '../engine/reconciliation.dart';
import '../engine/tools.dart';
import '../engine/verdict.dart';
import '../engine/version.dart';
import '../transforms/digest.dart';

/// Renders and publishes the cask that points at a release's assets.
///
/// A cask is executable Ruby, so rk emits one fixed structure from
/// validated values and never accepts a template. The cask points at
/// published assets, so it moves only after the release is public — and it is
/// a mutable pointer, so it moves forward under compare-and-swap rather than
/// being overwritten.
class HomebrewCask {
  /// Renders rk's complete cask for one GitHub-hosted release.
  ///
  /// Target adapters supply only release facts. Provider presentation stays
  /// here so staging, validation, and lost-stage recovery cannot drift.
  static String renderRelease({
    required String token,
    required String version,
    required String repository,
    required String tag,
    required Map<String, PlatformAsset> assets,
    required String executable,
  }) =>
      render(
        token: token,
        description: 'Released by rk',
        homepage: 'https://github.com/$repository',
        version: version,
        repository: repository,
        tag: tag,
        assets: assets,
        executable: executable,
      );

  /// Builds the cask text.
  ///
  /// Every value is either derived from the manifest or a digest of an asset
  /// rk produced; nothing here is interpolated from configuration.
  static String render({
    required String token,
    required String description,
    required String homepage,
    required String version,
    required String repository,
    required String tag,
    required Map<String, PlatformAsset> assets,
    required String executable,
  }) {
    if (assets.isEmpty) {
      throw ArgumentError('a Homebrew cask needs at least one archive');
    }
    const supportedPlatforms = {
      'macos-arm64',
      'linux-arm64',
      'linux-x64',
    };
    final unsupported = assets.keys.toSet().difference(supportedPlatforms);
    if (unsupported.isNotEmpty) {
      throw ArgumentError(
        'unsupported Homebrew cask platforms: ${unsupported.join(', ')}',
      );
    }
    for (final entry in assets.entries) {
      final expected = '$executable-$version-${entry.key}.tar.gz';
      if (entry.value.name != expected) {
        throw ArgumentError(
          'Homebrew cask archive ${entry.value.name} does not match $expected',
        );
      }
    }

    final macArm = assets['macos-arm64'];
    final linuxArm = assets['linux-arm64'];
    final linuxX64 = assets['linux-x64'];
    final hasLinux = linuxArm != null || linuxX64 != null;
    final releaseUrl = _releaseUrl(repository, tag);

    final buffer = StringBuffer()
      ..writeln('# Generated by rk. Edits are overwritten and will make the')
      ..writeln('# next release stop, because rk compares this file to the')
      ..writeln('# release it names.')
      ..writeln('cask "$token" do')
      ..writeln('  version "$version"')
      ..writeln();

    if (macArm != null) {
      buffer
        ..writeln('  on_macos do')
        ..writeln('    sha256 "${macArm.sha256}"')
        ..writeln('    url "${_url(repository, tag, macArm.name)}"')
        ..writeln()
        ..writeln('    depends_on arch: :arm64')
        ..writeln('  end')
        ..writeln();
    }

    if (hasLinux) {
      buffer.writeln('  on_linux do');
      if (linuxArm != null && linuxX64 != null) {
        buffer
          ..writeln('    arch arm: "arm64", intel: "x64"')
          ..writeln()
          ..writeln('    sha256 arm64_linux:  "${linuxArm.sha256}",')
          ..writeln('           x86_64_linux: "${linuxX64.sha256}"')
          ..writeln()
          ..writeln('    url "$releaseUrl/'
              '$executable-#{version}-linux-#{arch}.tar.gz"');
      } else {
        final asset = linuxArm ?? linuxX64!;
        final architecture = linuxArm != null ? 'arm64' : 'x86_64';
        buffer
          ..writeln('    sha256 "${asset.sha256}"')
          ..writeln('    url "${_url(repository, tag, asset.name)}"')
          ..writeln()
          ..writeln('    depends_on arch: :$architecture');
      }
      buffer
        ..writeln('  end')
        ..writeln();
    }

    buffer
      ..writeln('  name "${_escape(executable)}"')
      ..writeln('  desc "${_escape(description)}"')
      ..writeln('  homepage "${_escape(homepage)}"')
      ..writeln();
    if (macArm != null && !hasLinux) {
      buffer
        ..writeln('  depends_on :macos')
        ..writeln();
    } else if (macArm == null && hasLinux) {
      buffer
        ..writeln('  depends_on :linux')
        ..writeln();
    }
    buffer
      ..writeln('  binary "$executable"')
      ..writeln('end');

    return buffer.toString();
  }

  /// The canonical version claimed by bytes produced by this renderer.
  static Version? versionIn(List<int> bytes) {
    final String source;
    try {
      source = utf8.decode(bytes);
    } on FormatException {
      return null;
    }
    if (!source.startsWith('# Generated by rk.')) return null;
    final matches = RegExp(r'^  version "([^"]+)"$', multiLine: true)
        .allMatches(source)
        .toList();
    if (matches.length != 1) return null;
    final raw = matches.single.group(1)!;
    final parsed = Version.tryParse(raw);
    return parsed != null && parsed.canonical == raw ? parsed : null;
  }

  /// Casks are Ruby. Keep even future derived metadata inert if it contains
  /// string delimiters or interpolation syntax.
  static String _escape(String value) => value
      .replaceAll('\r', ' ')
      .replaceAll('\n', ' ')
      .replaceAll('\\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll(r'#{', r'\#{');

  static String _releaseUrl(String repository, String tag) =>
      'https://github.com/$repository/releases/download/'
      '${Uri.encodeComponent(tag)}';

  static String _url(String repository, String tag, String asset) =>
      '${_releaseUrl(repository, tag)}/${Uri.encodeComponent(asset)}';
}

class PlatformAsset {
  const PlatformAsset({required this.name, required this.sha256});
  final String name;
  final String sha256;
}

/// The exact public cask base an update was authorized against.
///
/// A missing cask and an existing zero-byte cask are different bases.
/// Existing bytes are represented by their digest so the authority is small
/// while still binding every byte observed by [HomebrewTarget.inspect].
class HomebrewUpdateAuthority {
  const HomebrewUpdateAuthority.absent({this.replacement}) : sha256 = null;

  HomebrewUpdateAuthority.existing(
    List<int> bytes, {
    this.replacement,
  }) : sha256 = Sha256.hex(bytes);

  final String? sha256;

  /// Intended bytes recovered from an authenticated public release when the
  /// local stage is gone. Null for ordinary stage-backed updates.
  final List<int>? replacement;

  /// Binds both the public compare-and-swap base and recovered replacement.
  String? get recoveryBinding {
    final bytes = replacement;
    if (bytes == null) return null;
    return '${sha256 ?? 'absent'}:${Sha256.hex(bytes)}';
  }

  bool accepts(List<int>? bytes) {
    final expected = sha256;
    if (expected == null) return bytes == null;
    return bytes != null && Sha256.hex(bytes) == expected;
  }

  String mismatch(List<int>? bytes) {
    final expected = sha256 == null ? 'no cask' : 'sha256 $sha256';
    final actual = bytes == null ? 'no cask' : 'sha256 ${Sha256.hex(bytes)}';
    return 'expected $expected; the fresh tap has $actual';
  }
}

/// Reads the cask exactly as Homebrew users receive it.
///
/// A cask is a mutable channel, not an immutable release artifact. RK advances
/// only a recognizable older generated cask and binds that act to the exact
/// bytes read here through [HomebrewUpdateAuthority].
class HomebrewTarget {
  HomebrewTarget({
    required this.tools,
    required this.tap,
    this.workingDirectory,
  });

  final Tools tools;
  final String tap;
  final String? workingDirectory;

  Future<Inspection> inspect({
    required String caskPath,
    required Version intendedVersion,
    required List<int>? expectedBytes,
    String? expectedSha256,
  }) async {
    if (expectedBytes != null && expectedSha256 != null) {
      throw ArgumentError(
        'Homebrew inspection accepts expected bytes or a digest, not both',
      );
    }
    if (expectedSha256 != null &&
        !RegExp(r'^[0-9a-f]{64}$').hasMatch(expectedSha256)) {
      throw ArgumentError('expected cask digest is not lowercase SHA-256');
    }
    final result = await tools.run(
      'gh',
      ['api', 'repos/$tap/contents/$caskPath'],
      workingDirectory: workingDirectory,
    );
    if (!result.ok) {
      if (result.summary.contains('(HTTP 404)')) {
        final readable = await tools.run(
          'gh',
          ['repo', 'view', tap, '--json', 'name'],
          workingDirectory: workingDirectory,
        );
        return readable.ok
            ? Inspection.absent(
                detail: 'no cask in the tap yet',
                evidence: const {'public cask': 'absent'},
                authority: HomebrewUpdateAuthority.absent(
                  replacement: expectedBytes,
                ),
              )
            : Inspection.unknown(
                'the tap $tap could not be read, so rk cannot tell what '
                'users install',
              );
      }
      return Inspection.unknown('the tap could not be read: ${result.summary}');
    }

    final List<int> publicBytes;
    try {
      final decoded = jsonDecode(result.stdout);
      final content = decoded is Map ? decoded['content'] : null;
      if (content is! String) {
        return const Inspection.unknown(
          'the tap answered something unreadable',
        );
      }
      publicBytes = base64Decode(content.replaceAll(RegExp(r'\s'), ''));
    } on Object catch (error) {
      return Inspection.unknown(
          'the tap answered something unreadable: $error');
    }

    final publicSha256 = Sha256.hex(publicBytes);
    final version = HomebrewCask.versionIn(publicBytes);
    return PublicReconciliation.movingChannel(
      label: 'the Homebrew cask',
      intendedVersion: intendedVersion,
      publishedVersion: version,
      payloadMatches:
          (expectedBytes != null && _sameBytes(publicBytes, expectedBytes)) ||
              (expectedSha256 != null && publicSha256 == expectedSha256),
      publishedIdentity: 'sha256:$publicSha256',
      unrecognizedDetail:
          'the Homebrew cask is not a recognizable rk-generated cask',
      advanceAuthority: HomebrewUpdateAuthority.existing(
        publicBytes,
        replacement: expectedBytes,
      ),
    );
  }

  static bool _sameBytes(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}

/// Moves a tap's cask forward, only from the state rk inspected.
class HomebrewTap {
  HomebrewTap({
    required this.tools,
    required this.tap,
    required this.checkout,
  });

  final Tools tools;

  /// `owner/homebrew-tap`.
  final String tap;

  /// Where the tap is cloned for this operation.
  final String checkout;

  /// Clones the tap, replaces the cask, and pushes — refusing if the
  /// remote moved under it, which is the compare-and-swap.
  ///
  /// The shared target inspection is the authorization read. The fresh clone
  /// must match that exact cask base, and a non-fast-forward rejection then
  /// catches movement after cloning.
  Future<TapOutcome> update({
    required String caskPath,
    required String contents,
    required String message,
    required HomebrewUpdateAuthority authority,
  }) async {
    // A checkout left by an interrupted run is stale by definition; the
    // compare-and-swap only means anything against a clone made now.
    final stale = Directory(checkout);
    if (stale.existsSync()) stale.deleteSync(recursive: true);

    final cloned = await tools.run('git', [
      'clone',
      '--depth',
      '1',
      'https://github.com/$tap.git',
      checkout,
    ]);
    if (!cloned.ok) return TapOutcome.failed(cloned.summary);

    // The API inspection authorized one exact base. The fresh clone must
    // still contain that base before rk writes anything; the push then guards
    // the remaining clone-to-remote gap with Git's fast-forward rule.
    final file = File('$checkout/$caskPath');
    final List<int>? existing;
    try {
      existing = file.existsSync() ? file.readAsBytesSync() : null;
    } on FileSystemException catch (error) {
      return TapOutcome.failed('the cloned cask could not be read: $error');
    }
    if (!authority.accepts(existing)) {
      return TapOutcome.failed(
        'the tap cask changed after rk inspected it; '
        '${authority.mismatch(existing)}. Re-run so rk can inspect the new '
        'public cask before updating it',
      );
    }

    // Unchanged is decided by bytes, before any git plumbing. The previous
    // version asked `git commit -a` to decide — which never stages a *new*
    // file, so a first-ever cask read as "already current" and nothing
    // was pushed. (It also wrote the file with `cat` and no stdin, so what
    // it committed was empty — [contents] was never used at all. Both are
    // why the tap step's test now asserts the pushed bytes.)
    final replacement = utf8.encode(contents);
    if (existing != null && HomebrewTarget._sameBytes(existing, replacement)) {
      return const TapOutcome.unchanged();
    }

    try {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(contents);
    } on FileSystemException catch (error) {
      return TapOutcome.failed('the cask could not be written: $error');
    }

    final added = await tools.run(
      'git',
      ['add', caskPath],
      workingDirectory: checkout,
    );
    if (!added.ok) return TapOutcome.failed(added.summary);

    final committed = await tools.run(
      'git',
      ['commit', '-m', message],
      workingDirectory: checkout,
    );
    if (!committed.ok) return TapOutcome.failed(committed.summary);

    final pushed = await tools.run(
      'git',
      const ['push'],
      workingDirectory: checkout,
    );
    if (!pushed.ok) {
      // Only an actual rejection is the compare-and-swap failing; an auth
      // failure or an unreachable remote wearing "the tap moved" prose
      // would send the operator hunting for a concurrent writer that does
      // not exist.
      final said = pushed.summary.toLowerCase();
      final rejected = said.contains('non-fast-forward') ||
          said.contains('fetch first') ||
          said.contains('rejected');
      return rejected
          ? TapOutcome.failed(
              'the tap moved while rk was working — re-running reads it '
              'fresh: ${pushed.summary}',
            )
          : TapOutcome.lostTrack('the push failed: ${pushed.summary}');
    }
    return const TapOutcome.updated();
  }
}

class TapOutcome {
  const TapOutcome._(this.problem, this.changed, this.mayHaveActed);
  const TapOutcome.updated() : this._(null, true, true);
  const TapOutcome.unchanged() : this._(null, false, false);
  const TapOutcome.failed(String problem) : this._(problem, false, false);
  const TapOutcome.lostTrack(String problem) : this._(problem, false, true);

  final String? problem;
  final bool changed;
  final bool mayHaveActed;
  bool get ok => problem == null;
}
