import '../engine/tools.dart';

/// Renders and publishes the formula that points at a release's assets.
///
/// A formula is executable Ruby, so rk emits one fixed structure from
/// validated values and never accepts a template. The formula points at
/// published assets, so it moves only after the release is public — and it is
/// a mutable pointer, so it moves forward under compare-and-swap rather than
/// being overwritten.
class HomebrewFormula {
  /// Builds the formula text.
  ///
  /// Every value is either derived from the manifest or a digest of an asset
  /// rk produced; nothing here is interpolated from configuration.
  static String render({
    required String className,
    required String description,
    required String homepage,
    required String version,
    required String repository,
    required String tag,
    required Map<String, PlatformAsset> assets,
    required String executable,
  }) {
    final buffer = StringBuffer()
      ..writeln('# Generated by rk. Edits are overwritten and will make the')
      ..writeln('# next release stop, because rk compares this file to the')
      ..writeln('# release it names.')
      ..writeln('class $className < Formula')
      ..writeln('  desc "${_escape(description)}"')
      ..writeln('  homepage "${_escape(homepage)}"')
      ..writeln('  version "$version"')
      ..writeln('  license :cannot_represent')
      ..writeln();

    final macArm = assets['macos-arm64'];
    if (macArm != null) {
      buffer
        ..writeln('  on_macos do')
        ..writeln('    on_arm do')
        ..writeln('      url "${_url(repository, tag, macArm.name)}"')
        ..writeln('      sha256 "${macArm.sha256}"')
        ..writeln('    end')
        ..writeln('  end')
        ..writeln();
    }

    final linuxX64 = assets['linux-x64'];
    final linuxArm = assets['linux-arm64'];
    if (linuxX64 != null || linuxArm != null) {
      buffer.writeln('  on_linux do');
      if (linuxX64 != null) {
        buffer
          ..writeln('    on_intel do')
          ..writeln('      url "${_url(repository, tag, linuxX64.name)}"')
          ..writeln('      sha256 "${linuxX64.sha256}"')
          ..writeln('    end');
      }
      if (linuxArm != null) {
        buffer
          ..writeln('    on_arm do')
          ..writeln('      url "${_url(repository, tag, linuxArm.name)}"')
          ..writeln('      sha256 "${linuxArm.sha256}"')
          ..writeln('    end');
      }
      buffer
        ..writeln('  end')
        ..writeln();
    }
    buffer
      ..writeln('  def install')
      ..writeln('    bin.install "$executable"')
      ..writeln('  end')
      ..writeln()
      ..writeln('  test do')
      ..writeln('    assert_match version.to_s, '
          'shell_output("#{bin}/$executable --version")')
      ..writeln('  end')
      ..writeln('end');

    return buffer.toString();
  }

  /// The Homebrew class name for a formula file.
  static String classNameFor(String executable) => executable
      .split(RegExp('[_-]'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join();

  static String _url(String repository, String tag, String asset) =>
      'https://github.com/$repository/releases/download/$tag/$asset';

  /// Values are derived, never interpolated, but a quote would still break the
  /// file — so one cannot appear.
  static String _escape(String value) => value.replaceAll('"', '');
}

class PlatformAsset {
  const PlatformAsset({required this.name, required this.sha256});
  final String name;
  final String sha256;
}

/// Moves a tap's formula forward, only from the state rk inspected.
class HomebrewTap {
  HomebrewTap({
    required this.tools,
    required this.tap,
    required this.checkout,
  });

  final Tools tools;

  /// `owner/homebrew-tap`.
  final String tap;

  /// Where the tap is cloned for this operation.
  final String checkout;

  /// Clones the tap, replaces the formula, and pushes — refusing if the
  /// remote moved under it, which is the compare-and-swap.
  Future<TapOutcome> update({
    required String formulaPath,
    required String contents,
    required String message,
  }) async {
    final cloned = await tools.run('git', [
      'clone',
      '--depth',
      '1',
      'https://github.com/$tap.git',
      checkout,
    ]);
    if (!cloned.ok) return TapOutcome.failed(cloned.summary);

    final file = '$checkout/$formulaPath';
    final wrote = await tools.run('sh', ['-c', 'cat > "$file"'],
        workingDirectory: checkout);
    if (!wrote.ok) return TapOutcome.failed('the formula could not be written');

    final committed = await tools.run(
      'git',
      ['commit', '-am', message],
      workingDirectory: checkout,
    );
    if (!committed.ok) {
      // Nothing to commit means the tap already holds this formula.
      if (committed.stdout.contains('nothing to commit')) {
        return const TapOutcome.unchanged();
      }
      return TapOutcome.failed(committed.summary);
    }

    // A non-fast-forward rejection is the compare-and-swap failing: the tap
    // moved since it was cloned, so what rk built was based on a stale view.
    final pushed = await tools.run(
      'git',
      const ['push'],
      workingDirectory: checkout,
    );
    if (!pushed.ok) {
      return TapOutcome.failed(
        'the tap moved while rk was working: ${pushed.summary}',
      );
    }
    return const TapOutcome.updated();
  }
}

class TapOutcome {
  const TapOutcome._(this.problem, this.changed);
  const TapOutcome.updated() : this._(null, true);
  const TapOutcome.unchanged() : this._(null, false);
  const TapOutcome.failed(String problem) : this._(problem, false);

  final String? problem;
  final bool changed;
  bool get ok => problem == null;
}
